export const AUDIT_REPORT_TYPES = {
  SET_AUDIT_REPORT: "SET_AUDIT_REPORT",
  SET_AUDIT_REPORT_INDIVIDUAL_DATA: "SET_AUDIT_REPORT_INDIVIDUAL_DATA",
  INDIVIDUAL_PUBLISHER_DATA_EDITED_STATUS:
    "INDIVIDUAL_PUBLISHER_DATA_EDITED_STATUS",
  RENDER_ADD_PUBLISHER_FORM: "RENDER_ADD_PUBLISHER_FORM",
  USER_LOGIN_STATUS:"USER_LOGIN_STATUS",
};
